### ISSUE TITLE
Object Sprite Touch-Up

### ISSUE THREAD

**Issue by ClarkStraws** [Latent-Arcana/project-dungeon#25]
# SET PIECES @yooaudrey

- [x] Basic Table
- [x] Basic Chair
- [x] Bookshelf
- [x] Standing Candelabra
- [x] Treasure Chest
- [x] Bed & Bedframe
- [x] Broken Debris (LONG)
- [x] Broken Debris (SHORT)
- [x] Armor Stand

# TRAPS @LatentArchitect

- [x] Shattered Chandelier
- [x] Rope Trap
- [x] Lightning Ball / Bolt (Tesla)
  - [x] electric_bolt_1
  - [x] electric_bolt_2
  - i figure 2 should probably work. let me know if we need all 4 in-game and I will revise the other 2
- [x] Tesla Trap
- [x] Sabre
- [x] Falchion

## Notes

- Spike-Pit Trap
  - would like to use for a different project or purpose but is not for this project
  - perspective requires the asset be completely redone if used in this
  - personally i think it looks pretty dope as is and should just be set aside for something else
  - lemme know if we still specifically want a spike trap. if we do, it will be a separate asset, not a revised/edited version of the one we currently have

**Comment by LatentArchitect** [comment]
Marking this closed as direction has shifted. See #53 for the new info
