### ISSUE TITLE
Item Sprite Touch-Up

### ISSUE THREAD

**Issue by SpicySoju2k20** [Latent-Arcana/project-dungeon#27]
## WEAPONS @LatentArchitect 

- [x] Saber
- [x] Battle Axe
- [x] Falchion
- [x] Heavy Mace
  - NOTE: literally nothing needed 
- [x] Halberd’s 

## ARMOR @yooaudrey 

- [x] Gambeson Robes
- [x] Elk's Hide Armor
- [x] Hauberk
- [x] Plackart
- [x] Laminar Plate Mail

## CONSUMABLES @LatentArchitect 

- [x] Elixir of Health
- [x] Vial of Pure Strength
- [x] Vial of Pure Speed
- [x] Vial of Pure Adrenaline
- [x] Vial of Pure Stamina

## SPECIAL WEAPONS @yooaudrey 

- [x] The Slayer of Dragons
- [x] The Almighty Doctrina
- [x] The Teeth that Bite Back
- [ ] The Honour's Lament
- [ ] The Left Hook, Right Hook

## SPECIAL ARMOR @LatentArchitect 

- [ ] The Mark XIV Phebos
- [x] The Garon's Fur
- [ ] The Wailing Lames
- [x] The Golden Belt and Shorts
- [x] #40

**Comment by LatentArchitect** [comment]
-- disregard -- 
this is me testing something out

**Comment by yooaudrey** [comment]
> -- disregard -- this is me testing something out

Ok. I am going to disregard. Not because I don't care, but because you asked me to.

**Comment by LatentArchitect** [comment]
Marking closed as direction has shifter. See #53 for updated tasks and info.
