### ISSUE TITLE
Enemy Sprite Touch-Up

### ISSUE THREAD

**Issue by SpicySoju2k20** [Latent-Arcana/project-dungeon#30]
**_ENEMIES_**

- [ ] Goblin @LatentArchitect 
- [ ] Kobold @yooaudrey 
- [ ] Skeleton @LatentArchitect 
- [ ] Bugbear @yooaudrey 
- [ ] Spirit @LatentArchitect

**Comment by LatentArchitect** [comment]
Marking this closed as direction has shifted. See #53 for the new info
