### ISSUE TITLE
Update Map-View tilemap in Unity

### ISSUE THREAD

**Issue by LatentArchitect** [Latent-Arcana/project-dungeon#32]

**Comment by LatentArchitect** [comment]
https://drive.google.com/drive/folders/1goxJTKmN75oNLi_uPbp_mRtyCpC132Cp

**Comment by LatentArtisan** [comment]
Looks better to me

![Image](https://github.com/user-attachments/assets/59731b1b-dad1-4ad2-9fce-a37ce9783828)

**Comment by LatentArtisan** [comment]
![Image](https://github.com/user-attachments/assets/1f2f4f49-0422-4ed6-a788-e4260976b722)
