### ISSUE TITLE
Object and Enemy Sprite - 16 Bit Update

### ISSUE THREAD

**Issue by SpicySoju2k20** [Latent-Arcana/project-dungeon#53]
# SET PIECES @yooaudrey

- [x] Basic Table
  [table-1.ase]
  [table-1.png]
- [x] Basic Chair
- [x] Bookshelf
  [bookshelf-1.ase]
  [bookshelf-1.png]
- [x] Standing Candelabra
- [x] Treasure Chest
- [x] Bed & Bedframe

~- [ ] Broken Debris (LONG)~

- [x] Broken Debris (SHORT)
  [scraps.ase]
  [scraps.png]
- [x] Armor Stand

---

# TRAPS @LatentArchitect

- [x] Shattered Chandelier
- [x] Rope Trap
- [x] Lightning Ball / Bolt (Tesla)
  - [x] electric_bolt_1
  - [x] electric_bolt_2
- [x] Tesla Trap
- [x] Sabre
- [x] Falchion
  [falchion.ase]
  [falchion.png]

---

**_ENEMIES_**

- [x] Goblin @LatentArchitect
- [x] Kobold @yooaudrey
- [x] Skeleton @LatentArchitect
  [skeleton.ase]
  [skeleton.png]
- [x] Bugbear @yooaudrey
  [bugbear-DRAFT.ase]
  [bugbear-DRAFT.png]
  - will need to touch up, current asset may not even be used as a bugbear
- [x] Spirit @LatentArchitect

---

# FOOTNOTE

## STAGES

1. draft --> "name-DRAFT.ase" or "WIP-name.ase" or "name-WIP.ase"
2. functional --> "name-num.ase" "name-num.png"
3. final --> "name-num-FIN.png"

## LINKS

https://drive.google.com/drive/u/3/folders/17eKGRPvw6tLjFbUT4EeXBlh9cMZwIb65

## Current Asset List 24-09-03

[battle-axe.ase]
[battle-axe.png]
[bookshelf-1.ase]
[bookshelf-1.png]
[bugbear-DRAFT.ase]
[bugbear-DRAFT.png]
[falchion.ase]
[falchion.png]
[floor-tile-1.ase]
[floor-tile-1.png]
[geometry-pattern-1.ase]
[geometry-pattern-1.png]
[pattern-1.ase]
[pattern-1.png]
[pattern-2.ase]
[pattern-2.png]
[pattern-3.ase]
[pattern-3.png]
[player-character-v1.png]
[player-character-v2.png]
[player-character-with_dir_]lighting.ase
[player-direction-down.ase]
[player-direction-down.png]
[player-direction-left.ase]
[player-direction-left.png]
[player-direction-right.ase]
[player-direction-right.png]
[player-direction-up.ase]
[player-direction-up.png]
[potion-health-1.ase]
[potion-health-1.png]
[potion-set.ase]
[potion-set.png]
[proto.ase]
[rapier.ase]
[rapier.png]
[scraps-1.ase]
[scraps-1.png]
[scraps.ase]
[scraps.png]
[skeleton.ase]
[skeleton.png]
[sprite-bundle-2.ase]
[sprite-bundle.ase]
[table-1.ase]
[table-1.png]
[table-2.ase]
[table-2.png]
[trap-1-WIP.ase]
[trap-1-WIP.png]

**Comment by SpicySoju2k20** [comment]
## Notes
- Spike-Pit Trap
  - would like to use for a different project or purpose but is not for this project
  - perspective requires the asset be completely redone if used in this
  - personally i think it looks pretty dope as is and should just be set aside for something else
  - lemme know if we still specifically want a spike trap. if we do, it will be a separate asset, not a revised/edited version of the one we currently have

**Comment by LatentArchitect** [comment]
@SpicySoju2k20 @ClarkStraws @yooaudrey updated for what is currently done and added asset list for what is in drive

**Comment by LatentArchitect** [comment]
@yooaudrey

| LINK | SPRITE | SPRITE | SPRITE | SPRITE | SPRITE |
| :--- | ------ | ------ | ------ | ------ | ------ |
| [Chair](../#chair) <br> <br> [Bed](#bed) <br> <br> [Candle](#candle) <br> <br> [Chest](#chest) <br> <br> [Armor Stand](#armor-stand) <br> <br> [Rat](#rat) <br> | ![Image](https://github.com/user-attachments/assets/0d043c52-d674-4406-adea-4f30d8bcee50) | ![Image](https://github.com/user-attachments/assets/391e5799-ab99-4fb6-9a36-fb1b5df164b0) | ![Image](https://github.com/user-attachments/assets/5844d144-f8c6-4034-8076-a209354b103c) | ![Image](https://github.com/user-attachments/assets/2d16d275-96e3-44b2-bb64-be5100d8a776) | ![Image](https://github.com/user-attachments/assets/06555c6d-e635-4cbb-ba93-2488bc063c11) |

#### Chair

> [!NOTE]
> 
> Chair -> PERFECTO

#### Bed

> [!NOTE]
> 
> Bed   -> Looks great!
> Only feedback is that the "boards"/frame of the bed is a bit too sharp. There are a few ways to do that, but honestly i think just bring the left leg over to the right by one pixel, and erasing the top two corners of the back frame would be about it.

#### Candle

> [!NOTE]
> Candle --> Looks sick. Would recommend deleting corner pixels on the bottom of the arms. Possibly a tiny bit lighter of a brown but I can do that later with color variant stuff.

#### Chest

> [!NOTE]
> Chest --> Good stuff. Need to delete corner pixels at the bottom corners and I may mess with the shape a bit

#### Armor Stand

> [!NOTE]
> Armor Stand --> LITERALLY PERFECT

#### Rat

> [!NOTE]
> Rat --> Other than round ing the one or two sharp edges, I think it looks great!!
