### ISSUE TITLE
16-Bit Assets (Tristan)

### ISSUE THREAD

**Issue by SpicySoju2k20** [Latent-Arcana/project-dungeon#74]
## Update the following Assets to 16-Bit:

- [x] Portal / Staircase for Travel to the next floor

### Special Armor Items

- [x] The Berserk's Armor
- [x] The Mark XIV Phebos
- [x] The Garon's Fur
- [x] The Wailing Fauld (Was Lames)
  ~The Golden Belt and Shorts~
  --note:-- i believe we may not be doing this item

### Special Weapon Items

- [x] The Slayer of Dragons
- [x] The Almighty Doctrina
- [x] The Teeth that Bite Back
- [x] The Honour's Lament
- [x] The Left Hook, Right Hook

**Comment by LatentArchitect** [comment]
done

https://drive.google.com/drive/u/2/folders/1mGUz3qoRVTauRMRtN6eKrtn9zULXQZiz
