### ISSUE TITLE
Explanation of Safe Rooms

### ISSUE THREAD

**Issue by ClarkStraws** [Latent-Arcana/project-dungeon#82]
Write out the defining characteristics of a safe room and what variations there may be:

- Does the player get healed?
- Does the player sleep/eat/drink potions
- What kinds of things would be in the safe room along with the bed/table/etc.
- What kinds of things define it as a safe room in general

**Comment by SpicySoju2k20** [comment]
https://www.notion.so/latentarchitect/ROOM-TYPES-846ab1c5a3cf4ae989753e6e2a36283a
