### ISSUE TITLE
UI - add interactions for hover/click on buttons

### ISSUE THREAD

**Issue by LatentArtisan** [Latent-Arcana/project-dungeon#85]

**Comment by SpicySoju2k20** [comment]
Kayleigh - Added a hover, confirmed working in Main Menu (unsure about Inventory Menu), currently working through next few items regarding Click.

Click - Needs to do something as well, such as a sound byte, possibly a visual effect.

@LatentArchitect to provide a mock-up of a Click Effect (CSS visual)
