### ISSUE TITLE
New Items

### ISSUE THREAD

**Issue by LatentArchitect** [Latent-Arcana/project-dungeon#91]

**Comment by LatentArchitect** [comment]
- [x] broken-pile.ase
- [x] broken-chair.ase
- [x] table-wide-alone.ase
- [x] mushroom-5.ase
- [x] mushroom-4.ase
- [x] mushroom-3.ase
- [x] desk-smol.ase
- [x] wood-pile.ase
- [x] spikes-2.ase
- [x] spikes.ase
- [x] bones-ribs.ase
- [x] mushroom-2.ase
- [x] vert-table.ase
- [x] mushroom.ase
- [x] moss-3.ase
- [x] moss-2.ase
- [x] moss.ase
- [x] hole.ase
- [x] rubble.ase
- [x] candles-new.ase
- [x] furnace.ase
- [x] crates.ase

**Comment by ClarkStraws** [comment]
- [x] Shrine (Multiple Variants)
- [x] Bear Trap
- [x] Alternative Color Fungus
- [x] Alternative Candles
- [x] Table + Chair Wide Sprite
- [x] Table + Chair Tall Sprite
- [x] Desk + Chair Sprite

**Comment by LatentArchitect** [comment]
## Shrines

### One
![Image](https://github.com/user-attachments/assets/3db98a29-63ad-40bd-a8e7-14021f104d5c)

### Two
![Image](https://github.com/user-attachments/assets/b69e5266-a3e7-4db5-a82f-fd17fe09983e)

### Three
![Image](https://github.com/user-attachments/assets/53068a0d-0ee5-4cf0-927b-28094df42ca9)

**Comment by LatentArchitect** [comment]
![Image](https://github.com/user-attachments/assets/71eb179b-a784-4154-bdba-47665f253d56)
