### ISSUE TITLE
Finish Adding Newest Objects/Items Sprites

### ISSUE THREAD

**Issue by ClarkStraws** [Latent-Arcana/project-dungeon#96]
<sub><a href="https://huly.app/guest/latarch?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJsaW5rSWQiOiI2NzJkNjQ4ZmU3Y2M1YTc4NTQyOTY0MDYiLCJndWVzdCI6InRydWUiLCJlbWFpbCI6IiNndWVzdEBoYy5lbmdpbmVlcmluZyIsIndvcmtzcGFjZSI6InctZ2l0aHVibGF0ZW50LWxhdGFyY2gtNjcyOTkyMWEtNTQ1ODFjZWE5YS1iYzgzNGEifQ.D5sYRzLzL6TiM8Gcmx4r8M5csLhfvwOhzBmoEphow4Q">Huly&reg;: <b>CART-95</b></a></sub>

**Comment by LatentArtisan** [comment]
@ClarkStraws are we done with this one?
